### ISSUE TITLE
Miscalculation

### ISSUE THREAD

**Issue by Frisket77** [nicholaskajoh/wp-energy-usage-calculator#1]
Total energy consumption incorrect.
![usage-calc](https://user-images.githubusercontent.com/37321472/51518106-da16f080-1dea-11e9-9874-b68ebc8275d8.png)

**Comment by nicholaskajoh** [comment]
Hi @Frisket77,
This plugin is no longer maintained. If you're willing to debug and fix the issue, I'll be glad to merge your PR and update the plugin.
Cheers!

**Comment by RichardMyers1984** [comment]
Hey Nicholas,

Thanks for responding. I created the issue because I'm learning how to use github, I will happily fix the issue.
Thanks again!

**Comment by nicholaskajoh** [comment]
That would be great! Feel free to [ask me any questions you might have](http://twitter.com/nicholaskajoh). I've not done WP dev in quite a while but I'll try my best to help.

**Comment by RichardMyers1984** [comment]
No problem!
Thanks Nicholas, really appreciate it.

**Comment by nicholaskajoh** [comment]
Hey @Frisket77, [the plugin](https://wordpress.org/plugins/wp-energy-usage-calculator/) has been updated :)
